#!/bin/bash
# Setup script to create .env.local with correct Supabase credentials

echo "🔧 Setting up Supabase environment variables..."
echo ""
echo "Please follow these steps:"
echo "1. Go to your Supabase dashboard"
echo "2. Click on your project"
echo "3. Go to Settings → API"
echo "4. Copy the Project URL and anon/public key"
echo ""
echo "Then run this command with your actual values:"
echo ""
echo "cat > .env.local << 'EOF'"
echo "VITE_SUPABASE_URL=https://your-actual-project-id.supabase.co"
echo "VITE_SUPABASE_PUBLISHABLE_KEY=your-actual-anon-key-here"
echo "EOF"
echo ""
echo "After creating .env.local, restart your development server:"
echo "npm run dev"